import { useCallback, useSyncExternalStore } from 'react'

// Standalone Filebase connection state. Deliberately has zero imports from the
// Storacha/W3Up stack — that integration is greyed out pending Storacha's
// maintenance status and is a candidate for deletion; nothing here should
// depend on it, or entangle its removal later.
//
// The only credential we ask for is an IPFS RPC API token, generated by the
// user in Filebase's Access Keys console (IPFS API tab). Those tokens are
// bucket-scoped at generation time, unlike the account-wide S3 access
// key/secret pair — so this is the credential that actually matches "bring
// your own scoped secret" rather than a master key in disguise.
//
// State lives in a module-level store (not per-call-site useState) so every
// component calling useFilebase() re-renders when another one connects or
// disconnects — e.g. the connect modal updating the nav bar immediately,
// without a page refresh.

const CREDS_KEY = 'hashchan_filebase_creds'

export interface FilebaseCreds {
  token: string
  // Display-only label the user types in when connecting (their own bucket's
  // name) — the token itself is already bucket-scoped server-side, so this
  // isn't used for auth, only so the nav bar can show "connected to bucket X".
  bucket?: string
}

const readCreds = (): FilebaseCreds | null => {
  try {
    const raw = localStorage.getItem(CREDS_KEY)
    return raw ? JSON.parse(raw) : null
  } catch {
    return null
  }
}

let cache: FilebaseCreds | null = readCreds()
const listeners = new Set<() => void>()

const setCache = (next: FilebaseCreds | null) => {
  cache = next
  listeners.forEach((listener) => listener())
}

const subscribe = (onStoreChange: () => void) => {
  listeners.add(onStoreChange)
  return () => listeners.delete(onStoreChange)
}

const getSnapshot = () => cache

export const useFilebase = () => {
  const creds = useSyncExternalStore(subscribe, getSnapshot)

  const connect = useCallback((next: FilebaseCreds) => {
    localStorage.setItem(CREDS_KEY, JSON.stringify(next))
    setCache(next)
  }, [])

  const disconnect = useCallback(() => {
    localStorage.removeItem(CREDS_KEY)
    setCache(null)
  }, [])

  return {
    connected: !!creds,
    creds,
    connect,
    disconnect,
  }
}
