// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HashChan$Type } from "./HashChan";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HashChan"]: HashChan$Type;
    ["contracts/HashChan.sol:HashChan"]: HashChan$Type;
  }

  interface ContractTypesMap {
    ["HashChan"]: GetContractReturnType<HashChan$Type["abi"]>;
    ["contracts/HashChan.sol:HashChan"]: GetContractReturnType<HashChan$Type["abi"]>;
  }
}
